language: java
jdk:
 - oraclejdk8
sudo: false
jobs:
  include:
    - stage: install
      script: "./gradlew setupCI"
    - stage: build
      script: "./gradlew build"
    - stage: test
      script: "./gradlew test"
    - stage: deploy
      if: tag IS present
      script: "./gradlew curseforge"
