language: java
jdk:
 - openjdk8
sudo: false
jobs:
  include:
    - stage: build
      script: "./gradlew setupCI build test"
    - stage: deploy
      if: tag IS present
      script: "./gradlew curseforge"
