modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="https://github.com/henne90gen/ChestCounter/issues"
authors="henne90gen"
license="GPLv3"

[[mods]]
modId="chestcounter"
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version="${file.jarVersion}"
displayName="Chest Counter"
# A URL to query for updates for this mod. See the JSON update specification <here>
# updateJSONURL="http://myurl.me/" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/chestcounter"
logoFile="icon.png"
description='''
This mod counts the items in the chests you open.
The counted items can later be searched through.
This way, you always know which items you have in stock and where.
'''

[[dependencies.chestcounter]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
